### PR TITLE
use JavaScript Standard Style

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by sonnyp** [comment]
@lloydwatkin standard isn't perfect but it's straightforward; would that work for you across node-xmpp modules?

**Comment by lloydwatkin** [comment]
Is this the module from @feross?

**Comment by sonnyp** [comment]
@lloydwatkin yes

**Comment by lloydwatkin** [comment]
Go for it, guy knows his semi-colons :)

**Comment by lloydwatkin** [comment]
We should use `standard` and implement `requireSafe` across everything (requireSafe replaces `grunt-nsp-package` I discovered)

**Comment by sonnyp** [comment]
@lloydwatkin how it is the library responsibility to check for security vulnerability in its dependencies?

**Comment by lloydwatkin** [comment]
As a user of `node-xmpp-*` I care if I'm using your library and it uses a vulnerable module, I don't care about downstream. We only need run on travis automatically.

**Comment by sonnyp** [comment]
@lloydwatkin ok seems a bit overkill to me as it implies all node modules should run the same security checks but I get the point; + it doesn't hurt.

**Pull request merged**
